//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedditRSS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedditRSSBotData
    {
        public RedditRSSBotData()
        {
            this.RedditSubmissions = new HashSet<RedditSubmission>();
        }
    
        public int ID { get; set; }
        public string FeedUrl { get; set; }
        public string Subreddit { get; set; }
        public int Interval { get; set; }
        public Nullable<int> RedditUserID { get; set; }
        public int StatusTypeID { get; set; }
    
        public virtual RedditUser RedditUser { get; set; }
        public virtual RedditRSSBotStatusType RedditRSSBotStatusType { get; set; }
        public virtual ICollection<RedditSubmission> RedditSubmissions { get; set; }
    }
}
