//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedditRSS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedditSubmission
    {
        public int ID { get; set; }
        public int RedditRSSBotDataID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Text { get; set; }
        public System.DateTime TimeSubmitted { get; set; }
    
        public virtual RedditRSSBotData RedditRSSBotData { get; set; }
    }
}
