//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedditRSS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedditRSSEntities : DbContext
    {
        public RedditRSSEntities()
            : base("name=RedditRSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<RedditRSSBotData> RedditRSSBotDatas { get; set; }
        public DbSet<RedditRSSBotStatusType> RedditRSSBotStatusTypes { get; set; }
        public DbSet<RedditSubmission> RedditSubmissions { get; set; }
        public DbSet<RedditUser> RedditUsers { get; set; }
    }
}
